import sqlite3
connection = sqlite3.connect("itstep_.sl3, 5")
cur = connection.cursor()
# cur.execute("CREATE TABLE first_table (name TEXT);")
# cur.execute("SELECT rowid, name FROM first_table;")
# cur.execute("INSERT INTO first_table (name)VALUES ('Ann');")
# cur.execute("INSERT INTO first_table (name)VALUES ('Kats');")
# cur.execute("INSERT INTO first_table (name)VALUES ('John');")
# cur.execute("INSERT INTO first_table (name)VALUES ('Nazar');")
connection.commit()
#cur.execute("SELECT rowid, name FROM first_table;")
cur.execute("SELECT rowid, name FROM first_table WHERE rowid=4;")
connection.commit()
res = cur.fetchall()
print(res)
# print(connection)
# print(cur)
connection.close()
